// Generated by CoffeeScript 1.4.0
(function() {
  var GP4InputStream, GTPInputStream,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  GTPInputStream = require('./GTPInputStream');

  GP4InputStream = (function(_super) {

    __extends(GP4InputStream, _super);

    function GP4InputStream() {
      return GP4InputStream.__super__.constructor.apply(this, arguments);
    }

    return GP4InputStream;

  })(GTPInputStream);

}).call(this);
