// Generated by CoffeeScript 1.4.0
(function() {
  var buffer, buffer_array, fs, stream, _;

  console.log('fuck');

  fs = require('fs');

  _ = require('underscore');

  buffer = new Buffer(100);

  stream = fs.createReadStream('kisstherain.gp5');

  buffer_array = [];

  stream.on('data', function(data) {
    return buffer_array.push(data);
  });

  stream.on('end', function(data) {
    var file_b, name, size1, size2;
    file_b = Buffer.concat(buffer_array);
    size1 = file_b.readUInt8(0);
    console.log(size1);
    name = file_b.toString('utf8', 1, size1);
    size2 = file_b.readUInt8(35);
    console.log(size2);
    console.log(name);
    name = file_b.toString('utf8', 36, 50);
    console.log(name);
    size2 = file_b.readUInt8(51);
    console.log(size2);
    size2 = file_b.readUInt8(52);
    console.log(size2);
    size2 = file_b.readUInt8(53);
    console.log(size2);
    name = file_b.toString('utf8', 54, 58);
    console.log(name);
    size2 = file_b.readUInt8(59);
    console.log(size2);
    size2 = file_b.readUInt8(60);
    console.log;
    size2 = file_b.readUInt8(51);
    console.log(size2);
    size2 = file_b.readUInt8(62);
    console.log(size2);
    name = file_b.toString('utf8', 63, 105);
    return console.log(name);
  });

}).call(this);
